// Generated by CIRCT firtool-1.76.0
module Adder(	// chisel/src/main/scala/examples/Adder.scala:5:7
  input  [7:0] io_a,	// chisel/src/main/scala/examples/Adder.scala:6:14
               io_b,	// chisel/src/main/scala/examples/Adder.scala:6:14
  output [7:0] io_c	// chisel/src/main/scala/examples/Adder.scala:6:14
);

  wire [7:0] io_a_0 = io_a;	// chisel/src/main/scala/examples/Adder.scala:5:7
  wire [7:0] io_b_0 = io_b;	// chisel/src/main/scala/examples/Adder.scala:5:7
  wire [7:0] io_c_0 = io_a_0 + io_b_0;	// chisel/src/main/scala/examples/Adder.scala:5:7, :12:16
  assign io_c = io_c_0;	// chisel/src/main/scala/examples/Adder.scala:5:7
endmodule

